spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/weathdb
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  server:
    port: 8080

  logging:
    level:
      root: info

  properties:
    weather-api-url: http://api.weatherapi.com/v1/current.json?q={q}&key={key}
    api-key: 8ae12118b5ca4f309ce110754252801
